
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jan 09 21:42:46 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 5;
  public static final int CONST = 46;
  public static final int ASTERISK = 24;
  public static final int SLASH = 25;
  public static final int GEQUAL = 30;
  public static final int CASE = 42;
  public static final int CONTINUE = 44;
  public static final int LPAREN = 8;
  public static final int GREATER = 32;
  public static final int SEMI = 7;
  public static final int LESS = 33;
  public static final int MINUS = 14;
  public static final int RPAREN = 9;
  public static final int DEQUALS = 28;
  public static final int DMINUS = 38;
  public static final int QMARK = 49;
  public static final int COMMA = 10;
  public static final int CLASS = 50;
  public static final int PLUS = 13;
  public static final int IF = 22;
  public static final int DOT = 27;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 6;
  public static final int EQUAL = 15;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int PERCENT = 26;
  public static final int DAMPERSAND = 35;
  public static final int NUMBER = 18;
  public static final int BREAK = 43;
  public static final int IDENT = 21;
  public static final int VOID = 16;
  public static final int SWITCH = 41;
  public static final int COLON = 17;
  public static final int LBRACE = 3;
  public static final int ELSE = 23;
  public static final int ENUM = 48;
  public static final int READ = 45;
  public static final int LEQUAL = 31;
  public static final int WHILE = 40;
  public static final int CHARCONST = 20;
  public static final int NEQUAL = 29;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 47;
  public static final int DPLUS = 37;
  public static final int BOOLCONST = 19;
  public static final int PROG = 2;
  public static final int DO = 39;
  public static final int DVBAR = 36;
  public static final int PRINT = 11;
}

