
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int IF = 16;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;
  public static final int BREAK = 18;
  public static final int CLASS = 19;
  public static final int ENUM = 20;
  public static final int CONST = 21;
  public static final int SWITCH = 22;
  public static final int DO = 23;
  public static final int WHILE = 24;
  public static final int NEW = 25;
  public static final int READ = 26;
  public static final int EXTENDS = 27;
  public static final int CONTINUE = 28;
  public static final int CASE = 29;
  public static final int MINUS = 30;
  public static final int ASTERISK = 31;
  public static final int SLASH = 32;
  public static final int PERCENT = 33;
  public static final int DEQUALS = 34;
  public static final int NEQUAL = 35;
  public static final int GREATER = 36;
  public static final int GEQUAL = 37;
  public static final int LESS = 38;
  public static final int LEQUAL = 39;
  public static final int DAMPERSAND = 40;
  public static final int DVBAR = 41;
  public static final int DPLUS = 42;
  public static final int DMINUS = 43;
  public static final int DOT = 44;
  public static final int LBRACKET = 45;
  public static final int RBRACKET = 46;
  public static final int BOOLCONST = 47;
  public static final int CHARCONST = 48;
  public static final int QMARK = 49;
  public static final int COLON = 50;
}
